- books/assembly-overview.adoc
- books/master.adoc
- books/ref-overview-document-conventions.adoc
- books/ref-overview-key-features.adoc
- books/ref-overview-supported-configurations.adoc
This PR adds the overview assembly with following chapters:
* Overview
* Key Features
* Supported Configurations
* Document Conventions
> Add overview assembly

- books/assembly-getting-started.adoc
- books/common/attributes.adoc
- books/master.adoc
- books/proc-configuring-amq-streams.adoc
- books/proc-downloading-amq-streams.adoc
- books/proc-downloading-and-installing-amq-streams.adoc
- books/proc-installing-amq-streams.adoc
- books/proc-running-single-node-amq-streams-cluster.adoc
- books/proc-stopping-amq-streams.adoc
- books/proc-using-amq-streams.adoc
This PR adds the Getting Started assembly.
> Add _Getting started_ assembly

- books/assembly-configuring-kafka.adoc
- books/con-kafka-broker-id-configuration.adoc
- books/con-kafka-commit-log-configuration.adoc
- books/con-kafka-listener-configuration.adoc
- books/con-kafka-logging.adoc
- books/con-kafka-zookeeper-configuration.adoc
- books/master.adoc
- books/proc-running-multinode-kafka-cluster.adoc
- books/proc-running-multinode-zookeeper-cluster.adoc
- books/proc-running-single-node-amq-streams-cluster.adoc
This PR adds the Kafka configuration section.
> Add Kafka configuration section

- books/assembly-configuring-kafka.adoc
- books/assembly-configuring-zookeeper.adoc
- books/con-kafka-broker-id-configuration.adoc
- books/con-kafka-commit-log-configuration.adoc
- books/con-kafka-listener-configuration.adoc
- books/con-kafka-logging.adoc
- books/con-kafka-zookeeper-configuration.adoc
- books/con-zookeeeper-cluster-configuration.adoc
- books/con-zookeeper-additional-configuration.adoc
- books/con-zookeeper-basic-configuration.adoc
- books/con-zookeeper-logging.adoc
- books/master.adoc
- books/proc-running-multinode-kafka-cluster.adoc
- books/proc-running-multinode-zookeeper-cluster.adoc
- books/proc-running-single-node-amq-streams-cluster.adoc
- books/ref-zookeeper-additional-configuration.adoc
This PR adds the Zookeeper configuration section.
> Add Zookeeper configuration section

- books/assembly-configuring-kafka.adoc
- books/assembly-configuring-zookeeper-authentication.adoc
- books/assembly-configuring-zookeeper.adoc
- books/assembly-kafka-zookeeper-authentication.adoc
- books/assembly-kafka-zookeeper-authorization.adoc
- books/con-kafka-zookeeper-authentication-jaas.adoc
- books/con-kafka-zookeeper-authorization-enabling-acls.adoc
- books/con-zookeeper-authorization.adoc
- books/con-zookeeper-sasl-authentication.adoc
- books/con-zookeeper-tls.adoc
- books/proc-kafka-enable-zookeeper-auth.adoc
- books/proc-kafka-enabling-zookeeper-acls.adoc
- books/proc-kafka-migrating-zookeeper-acls.adoc
- books/proc-zookeeper-enable-client-to-server-auth-digest-md5.adoc
- books/proc-zookeeper-enable-server-to-server-auth-digest-md5.adoc
Thi PR adds information about Zoopkeeper authentication.
> Add information about Zookeeper authentication

- books/assembly-topics.adoc
- books/con-internal-topics.adoc
- books/con-message-retention.adoc
- books/con-partitions-and-topics.adoc
- books/con-topic-autocreation.adoc
- books/con-topic-configuration.adoc
- books/con-topic-deletion.adoc
- books/master.adoc
- books/proc-creating-a-topic.adoc
- books/proc-deleting-a-topic.adoc
- books/proc-describing-a-topic.adoc
- books/proc-modifying-a-topic.adoc
- books/ref-topic-configuration.adoc
This PR adds a section about topics and topic management.
> Add chapter about topics

- books/assembly-configuring-kafka.adoc
- books/assembly-kafka-encryption-and-authentication.adoc
- books/con-kafka-authentication.adoc
- books/con-kafka-securing-listeners.adoc
- books/con-kafka-tls-encryption.adoc
- books/proc-kafka-adding-scram-users.adoc
- books/proc-kafka-deleting-scram-users.adoc
- books/proc-kafka-enable-plain-authentication.adoc
- books/proc-kafka-enable-scram-authentication.adoc
- books/proc-kafka-enable-tls-client-authentication.adoc
- books/proc-kafka-enable-tls-encryption.adoc
This PR adds a new docu section about Kafka encryption and authentication.
> Add encryption and authentication

- books/assembly-kafka-connect-distributed.adoc
- books/assembly-kafka-connect-standalone.adoc
- books/assembly-kafka-connect.adoc
- books/con-kafka-connect-connector-plugins.adoc
- books/master.adoc
- books/proc-adding-connector-plugins.adoc
- books/proc-creating-connector-kafka-connect-distributed.adoc
- books/proc-deleting-connector-kafka-connect-distributed.adoc
- books/proc-running-kafka-connect-distributed.adoc
- books/proc-running-kafka-connect-standalone.adoc
- books/proc-scaling-up-a-kafka-cluster.adoc
- books/ref-kafka-connect-distributed-configuration.adoc
- books/ref-kafka-connect-distributed-connector-configuration.adoc
- books/ref-kafka-connect-standalone-configuration.adoc
- books/ref-kafka-connect-standalone-connector-configuration.adoc
Add chapter about Kafka Connect.
> Add Kafka Connect docs

- books/assembly-overview.adoc
- books/con-considerations-for-data-storage.adoc
This pull request adds a new concept module detailing some considerations for provisioning storage for AMQ Streams on Red Hat Enterprise Linux.
> [DOCS] Create storage considerations for Streams on RHEL

- books/common/attributes.adoc
This Pr updates the versions of the Kafka Clients and Kafka Streams to what we currently expect in the GA release.
> The version of Kafka clients and Kafka Streams should be updated for AMQ Streams 1.1.0

- books/con-considerations-for-data-storage.adoc
Modified content for data storage considerations
> [DOC] New and modified content for ENTMQST-555

- books/assembly-getting-started.adoc
- books/assembly-overview.adoc
- books/con-considerations-for-data-storage.adoc
Storage considerations now sits with deployment content
> Move Storage considerations section

- books/assembly-upgrade-1-1-0.adoc
- books/con-strategies-for-upgrading-clients.adoc
- books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
- books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
- books/proc-updating-zookeeper-binaries.adoc
- books/proc-upgrading-clients-to-new-kafka-version.adoc
- books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
Documentation
Updates for the upgrade chapter
> [DOC] Updates to the upgrade chapter [ENTMQST-781]

- books/common/attributes.adoc
- books/proc-downloading-amq-streams.adoc
- books/proc-updating-zookeeper-binaries.adoc
- books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
Removed the v1.1.0 specific attribute.
> Removed the v1.1.0 specific attribute.

- books/assembly-upgrade-1-1-0.adoc
- books/common/attributes.adoc
- books/proc-installing-amq-streams.adoc
- books/proc-updating-kafka-brokers-to-new-inter-broker-protocol-version.adoc
- books/proc-updating-kafka-brokers-to-new-message-format-version.adoc
- books/proc-updating-zookeeper-binaries.adoc
- books/proc-upgrading-clients-to-new-kafka-version.adoc
- books/proc-upgrading-kafka-brokers-to-amq-streams-1-1-0.adoc
- books/proc-upgrading-kafka-connect-to-amq-streams-1-1-0.adoc
This pull request changes version `1.1.0` to `1.1.x` throughout.
I created the `rh-messaging:streams-1.1.x-amq-7.3` release branch because it didn't already exist.
> Changed 1.1.0 to 1.1.x throughout

- books/proc-running-multinode-kafka-cluster.adoc
Doc fix for format issues in the section on Running a multi-node Kafka cluster
> [DOC] Format fixes for Running a multi-node Kafka cluster

- books/proc-kafka-adding-scram-users.adoc
- books/proc-kafka-deleting-scram-users.adoc
- books/proc-kafka-enable-plain-authentication.adoc
- books/proc-kafka-enable-scram-authentication.adoc
- books/proc-kafka-enable-tls-client-authentication.adoc
- books/proc-kafka-enable-tls-encryption.adoc
- books/proc-upgrading-kafka-connect-to-amq-streams.adoc
- books/proc-upgrading-zookeeper-binaries.adoc
- books/ref-kafka-connect-distributed-configuration.adoc
- books/ref-kafka-connect-standalone-configuration.adoc
> Link fixes

- books/con-sending-requests-to-kafka-bridge.adoc
- books/master.adoc
- books/proc-installing-kafka-bridge.adoc
- books/ref-topic-config.adoc
Minor changes from review before releasing doc for testing
> 1.2 - minor edits from editorial review

- books/assembly-using-the-kafka-bridge.adoc
- books/con-loggers-kafka-bridge.adoc
- books/con-overview-of-kafka-bridge.adoc
Add the concept on "Configuring loggers for the AMQ Streams Kafka Bridge" to the Kafka Bridge assembly.
> Added Kafka bridge loggers documentation

- books/assembly-configuring-kafka.adoc
- books/assembly-kafka-authorization.adoc
- books/assembly-kafka-zookeeper-authorization.adoc
- books/con-kafka-authorization-simple.adoc
- books/con-kafka-zookeeper-authorization-enabling-acls.adoc
- books/proc-kafka-authorization-add-rules.adoc
- books/proc-kafka-authorization-list-rules.adoc
- books/proc-kafka-authorization-remove-rules.adoc
- books/proc-kafka-enable-authorization.adoc
- books/proc-kafka-enabling-zookeeper-acls.adoc
- books/proc-kafka-migrating-zookeeper-acls.adoc
- books/ref-topic-configuration.adoc
New **_Authorization_** section for Configuring Kafka chapter.
We had some content that had not been added. I used that as a basis, reviewing against online material.
There is maybe more we want to say, but we have the basic configuration of SimpleACLAuthorizer.
> Kafka authorization using SimpleACLAuthorizer

- books/con-kafka-authorization-simple.adoc
- books/con-partitions-and-topics.adoc
Following QE test of the procedures, clarification of the requirements for authentication before you define ACLs.
> ACL authorization

- books/assembly-getting-started.adoc
- books/assembly-kafka-exporter.adoc
- books/common/attributes.adoc
- books/kafka-exporter/con-kafka-exporter-alerts.adoc
- books/kafka-exporter/con-kafka-exporter-grafana.adoc
- books/kafka-exporter/con-kafka-exporter-lag.adoc
- books/kafka-exporter/proc-kafka-exporter-enabling.adoc
- books/kafka-exporter/proc-kafka-exporter-running.adoc
- books/kafka-exporter/ref-kafka-exporter-metrics.adoc
- books/master.adoc
The section describe the metrics scraped by the Kafka Exporter and how you enable it to present the data in Grafana.
Assumes that Prometheus and Grafana is set up.
> New Kafka Exporter section
